# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_apps.ipynb.

# %% auto 0
__all__ = ['pdf_corpus_chatbot_llamaindex', 'pdf_corpus_chatbot_langchain']

# %% ../nbs/01_apps.ipynb 2
from .tools.pdf_corpus_qa_llamaindex import PdfFileCollectionLlamaIndexChatBot

# %% ../nbs/01_apps.ipynb 3
def pdf_corpus_chatbot_llamaindex(doc_dir, 
        llm_name, 
        embed_model_name="BAAI/bge-small-en-v1.5", 
        sentence_window_size=3):
    
    chatbot = PdfFileCollectionLlamaIndexChatBot(doc_dir, 
                llm_name,
                embed_model_name=embed_model_name, 
                sentence_window_size=sentence_window_size)
    chatbot.run_gradio()

# %% ../nbs/01_apps.ipynb 4
def pdf_corpus_chatbot_langchain(doc_dir, 
        llm_name, 
        embed_model_name="BAAI/bge-small-en-v1.5", 
        sentence_window_size=3):
    
    chatbot = PdfFileCollectionLlamaIndexChatBot(doc_dir, 
                llm_name,
                embed_model_name=embed_model_name, 
                sentence_window_size=sentence_window_size)
    chatbot.run_gradio()
