# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_apps.ipynb.

# %% auto 0
__all__ = ['paperqa_chatbot']

# %% ../nbs/01_apps.ipynb 2
import os
from .apps.chat import AlhazenAgentChatBot

# %% ../nbs/01_apps.ipynb 3
def paperqa_chatbot(loc, db_name):
    
    os.environ['LOCAL_FILE_PATH'] = loc

    os.environ['ALHAZEN_DB_NAME'] = db_name

    """Run a chatbot based on the paperqa methodology:
    
    `python -m fire alhazen.apps paperqa_chatbot '/path/to/local/files/' 'ALHAZEN_DB_NAME'
    """
    
    chatbot = AlhazenAgentChatBot()
    chatbot.run_gradio()
