# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': 'https://alzhazen.github.io',
                'git_url': 'https://github.com/alzhazen/',
                'lib_path': ''},
  'syms': {'alzhazen.core': {'alzhazen.core.foo': ('core.html#foo', 'alzhazen/core.py')}, 'alzhazen.setup': {}}}
