# Choose a python version that you know works with your application
FROM python:3.11-slim

USER root

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    git python-pip 

WORKDIR /app

# Copy the library files to the working directory
COPY . /app

RUN pip install hatch

# Create a non-root user and switch to it
RUN useradd -m app_user
USER app_user

RUN pip install -e .

EXPOSE 6720

CMD [ "marimo", "run", "marimo/000_metadata_extraction_map.py", "--host", "0.0.0.0", "-p", "6720" ]