services:
  alhazen: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:2718:2718"
    volumes:
      - .:/home/jovyan/alhazen
      - ./nbs/cookbook:/home/jovyan/work
      - ~/.cache/huggingface:/home/jovyan/.cache/huggingface
      - $LOCAL_FILE_PATH:/home/jovyan/files
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
      - LOCAL_FILE_PATH=/home/jovyan/files
      - DATABRICKS_API_KEY=$DATABRICKS_API_KEY
      - GROQ_API_KEY=$GROQ_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
    depends_on:
      db:
        condition: service_healthy
  db:
    image: pgvector/pgvector:pg14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=localhost
    healthcheck:
      test: "pg_isready -q -U postgres" 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
  work:
