# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/13_pdf_text_extractor.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/13_pdf_text_extractor.ipynb 2
'''from pypdf import PdfReader
import dataclasses
from typing import List, Tuple, Any, Dict
'''

# %% ../../nbs/13_pdf_text_extractor.ipynb 3
'''
@dataclasses.dataclass
class PdfDoc:
    """A class that provides structure for full text papers specified under the JATS 'nxml' format."""

    # The location of the file
    url: str

    # The identifier of the paper
    ft_id: str

    # Plain text of the paper's contents
    text: str
      
    def __init__(self, ft_id, url):
        self.ft_id = ft_id

        reader = PdfReader(url)
        number_of_pages = len(reader.pages)
        text = ''
        for p in reader.pages:
            text += p.extract_text()
        self.text = text
'''
