# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/12_metadata_extraction_agent.ipynb.

# %% auto 0
__all__ = ['search', 'tools']

# %% ../../nbs/12_metadata_extraction_agent.ipynb 2
from langchain.agents import AgentExecutor, BaseSingleActionAgent, Tool
from langchain.schema import AgentAction, AgentFinish
from langchain.utilities import SerpAPIWrapper

import os

from typing import Any, List, Tuple, Union


# %% ../../nbs/12_metadata_extraction_agent.ipynb 3
search = SerpAPIWrapper()
tools = [
    Tool(
        name="Search",
        func=search.run,
        description="useful for when you need to answer questions about current events",
        return_direct=True,
    )
]
