erDiagram
Entity {
    string id  
    uriorcurieList iri  
    string type  
}
NamedThing {
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
InformationContentEntity {
    date creation_date  
    string content  
    string format  
    stringList provenance  
    uriorcurieList xref  
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
InformationResource {
    date creation_date  
    string content  
    string format  
    stringList provenance  
    uriorcurieList xref  
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
ScientificKnowledgeCollection {
    date creation_date  
    string content  
    string format  
    stringList provenance  
    uriorcurieList xref  
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
ScientificKnowledgeExpression {
    date publication_date  
    ScientificKnowledgeExpressionType type  
    date creation_date  
    string content  
    string format  
    stringList provenance  
    uriorcurieList xref  
    string name  
    string id  
    uriorcurieList iri  
}
ScientificKnowledgeItem {
    date creation_date  
    string content  
    string format  
    stringList provenance  
    uriorcurieList xref  
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
ScientificKnowledgeFragment {
    integer offset  
    integer length  
    date creation_date  
    string content  
    string format  
    stringList provenance  
    uriorcurieList xref  
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
Note {
    string format  
    NoteType type  
    date creation_date  
    string content  
    stringList provenance  
    uriorcurieList xref  
    string name  
    string id  
    uriorcurieList iri  
}
Author {
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
Organization {
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
City {
    string name  
    string id  
    uriorcurieList iri  
    string type  
}
Country {
    string name  
    string id  
    uriorcurieList iri  
    string type  
}

InformationContentEntity ||--}o Author : "authors"
InformationContentEntity ||--}o Note : "has notes"
InformationResource ||--}o Author : "authors"
InformationResource ||--}o Note : "has notes"
ScientificKnowledgeCollection ||--}o ScientificKnowledgeExpression : "has members"
ScientificKnowledgeCollection ||--}o Author : "authors"
ScientificKnowledgeCollection ||--}o Note : "has notes"
ScientificKnowledgeExpression ||--}o ScientificKnowledgeItem : "has representation"
ScientificKnowledgeExpression ||--}o ScientificKnowledgeCollection : "member of"
ScientificKnowledgeExpression ||--}o Author : "authors"
ScientificKnowledgeExpression ||--}o Note : "has notes"
ScientificKnowledgeItem ||--|o ScientificKnowledgeExpression : "representation of"
ScientificKnowledgeItem ||--}o ScientificKnowledgeFragment : "has part"
ScientificKnowledgeItem ||--}o Author : "authors"
ScientificKnowledgeItem ||--}o Note : "has notes"
ScientificKnowledgeFragment ||--|o ScientificKnowledgeItem : "part of"
ScientificKnowledgeFragment ||--}o Author : "authors"
ScientificKnowledgeFragment ||--}o Note : "has notes"
Note ||--}o InformationContentEntity : "is about"
Note ||--}o Author : "authors"
Note ||--}o Note : "has notes"
Author ||--}o Organization : "affiliations"
Organization ||--}o City : "city"
Organization ||--}o Country : "country"

