erDiagram
Entity {
    string id  
    string iri  
    stringList type  
    string type_str  
}
NamedThing {
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
InformationContentEntity {
    string license  
    string rights  
    string format  
    date creation_date  
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
ScientificKnowledgeExpression {
    string id  
    string title  
    string abstract  
    date publication_date  
    string license  
    string rights  
    string format  
    date creation_date  
    string name  
    uriorcurieList xref  
    string iri  
    stringList type  
    string type_str  
}
ScientificPublication {
    string doi  
    ScientificPublicationType type_str  
    string id  
    string title  
    string abstract  
    date publication_date  
    string license  
    string rights  
    string format  
    date creation_date  
    string name  
    uriorcurieList xref  
    string iri  
    stringList type  
}
InformationResource {
    string id  
    string name  
    uriorcurieList xref  
    string license  
    string rights  
    string format  
    date creation_date  
    string iri  
    stringList type  
    string type_str  
}
ScientificKnowledgeCollection {
    string id  
    string name  
    string logical_query  
    date creation_date  
    string license  
    string rights  
    string format  
    uriorcurieList xref  
    string iri  
    stringList type  
    string type_str  
}
ScientificPublicationCollection {
    string id  
    string name  
    string logical_query  
    date creation_date  
    string license  
    string rights  
    string format  
    uriorcurieList xref  
    string iri  
    stringList type  
    string type_str  
}
ScientificKnowledgeFragment {
    string license  
    string rights  
    string format  
    date creation_date  
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
Selector {
    string license  
    string rights  
    string format  
    date creation_date  
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
OffsetTextSelector {
    integer offset  
    integer length  
    string license  
    string rights  
    string format  
    date creation_date  
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
Note {
    string format  
    NoteType type_str  
    string license  
    string rights  
    date creation_date  
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
}
NameValuePair {
    string variable  
    string value  
    string license  
    string rights  
    string format  
    date creation_date  
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
Person {
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
Author {
    string orcid  
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
Organization {
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
City {
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}
Country {
    string name  
    uriorcurieList xref  
    string id  
    string iri  
    stringList type  
    string type_str  
}

InformationContentEntity ||--}o Note : "provenance"
ScientificKnowledgeExpression ||--}o ScientificKnowledgeFragment : "has part"
ScientificKnowledgeExpression ||--}o Author : "authors"
ScientificKnowledgeExpression ||--}o Note : "provenance"
ScientificPublication ||--}o ScientificKnowledgeFragment : "has part"
ScientificPublication ||--}o Author : "authors"
ScientificPublication ||--}o Note : "provenance"
InformationResource ||--}o Note : "provenance"
ScientificKnowledgeCollection ||--}o InformationResource : "information sources"
ScientificKnowledgeCollection ||--}o Note : "provenance"
ScientificPublicationCollection ||--}o ScientificPublication : "has part"
ScientificPublicationCollection ||--}o InformationResource : "information sources"
ScientificPublicationCollection ||--}o Note : "provenance"
ScientificKnowledgeFragment ||--|o ScientificKnowledgeExpression : "part of"
ScientificKnowledgeFragment ||--|o Selector : "selector"
ScientificKnowledgeFragment ||--}o Note : "provenance"
Selector ||--}o Note : "provenance"
OffsetTextSelector ||--}o Note : "provenance"
Note ||--}o Entity : "is about"
Note ||--}o Author : "authors"
Note ||--}o NameValuePair : "structured_content"
Note ||--}o Note : "provenance"
NameValuePair ||--}o Note : "provenance"
Author ||--}o Organization : "affiliations"
Organization ||--}o City : "city"
Organization ||--}o Country : "country"

